[Authentication]
subscription_id="sub_id"
resource_group="resource_group"
user_assigned_identity="user_assigned_identity"
tenant_id="tenant_id"
batch_application_id="batch_application_id"    #previously client_id
batch_object_id="batch_object_id"     #previously principal_id
sp_application_id="sp_application_id"    #previously application_id
vault_url="https://vault_name.vault.azure.net/"
vault_sp_secret_id="CFA-SECRET_ID"
subnet_id="subnet_id"

[Batch]
batch_account_name="batch_account_name"
batch_service_url="batch_service_url"
pool_vm_size="STANDARD_A2_V2"  # VM Type/Size

[Storage]
storage_account_name="storage_account_name"
storage_account_url="storage_account_url"
