name: Python Unit Tests with Coverage

on:
  push:
    branches: [ unit_tests ]
  pull_request:
    branches: [ unit_tests ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install poetry
        run: pip install poetry

      - name: install package
        run: poetry install --with test

      - name: Run tests with coverage
        run: coverage run -m pytest

      - name: Generate coverage report
        run: coverage report -m
